const express = require("express")
const postrouter = express.Router()
const multer = require("multer")
const upload = multer({storage:multer.memoryStorage()})
const verifyuser = require("../middlewares/user")
const postcontroller = require("../controllers/post.controller")
const { verify } = require("jsonwebtoken")

postrouter.post("/", verifyuser, upload.single("image"), postcontroller.createpostcontroller)
postrouter.get("/" , verifyuser,postcontroller.getpostcontroller )
postrouter.get("/details/:postid", verifyuser, postcontroller.getpostdetailscontroller)
postrouter.post("/likes/:postid",verifyuser,postcontroller.likepostcontroller)
postrouter.post("/unlike/:postid",verifyuser,postcontroller.unlikepostcontroller )
postrouter.get("/feed", verifyuser, postcontroller.feedpostcontroller)
module.exports = postrouter